//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rt_det_paquetes_skus
    {
        public int Id { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public int rt_paquete_Id { get; set; }
        public int skus_Id { get; set; }
    
        public virtual rt_paquete rt_paquete { get; set; }
        public virtual skus skus { get; set; }
    }
}
