//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rt_paquete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rt_paquete()
        {
            this.rt_det_paquetes_skus = new HashSet<rt_det_paquetes_skus>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string Guia { get; set; }
        public string Paquete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rt_det_paquetes_skus> rt_det_paquetes_skus { get; set; }
    }
}
